  # Ollama Configuration for GoFigure Murder Mystery Game
  ollama:
    host: "http://localhost:11434"    # Ollama server URL
    model: "llama3.2:latest"         # Model to use for character responses
    timeout: 30                       # Timeout in seconds for API calls

  # You can also set these via environment variables:
  # GOFIGURE_OLLAMA_HOST=http://localhost:11434
  # GOFIGURE_OLLAMA_MODEL=llama3.2
  # GOFIGURE_OLLAMA_TIMEOUT=30